_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone
  # WEIGHTS: /content/BoostTrack/external/weights/mot17_sbs_S50.pth
  WEIGHTS: /content/Fawry-Surveillance-Competition/Tracking/fast_reid/weights/mot17_sbs_S50.pth

DATASETS:
  NAMES: ("MOT20",)
  TESTS: ("MOT20",)

OUTPUT_DIR: "/content/drive/MyDrive/MIA AI/MOT20/logs"
