_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone
  # WEIGHTS: /kaggle/working/BoostTrack/external/weights/mot17_sbs_S50.pth

DATASETS:
  NAMES: ("MOT20",)
  TESTS: ("MOT20",)

OUTPUT_DIR: /kaggle/working/BoostTrack/external/fast_reid/logs/MOT20/
